
#ifndef _HACHI_CONFIG_H
#define _HACHI_CONFIG_H

#define HACHI_CONFIG_XMODEM_PURGE_TIMEOUT 100
#define HACHI_CONFIG_XMODEM_BOOT_TIMEOUT 100
#define HACHI_CONFIG_XMODEM_INITIAL_PACKET_TIMEOUT 3000
#define HACHI_CONFIG_XMODEM_PACKET_TIMEOUT 3000
#define HACHI_CONFIG_XMODEM_DATA_TIMEOUT 1000
#define HACHI_CONFIG_XMODEM_RETRY 9

#endif // _HACHI_CONFIG_H
